version: "2"
services:
  node:
    build: .
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    ports:
      - "4200:4200"
      - '49153:49153'
    command: "ng serve --host 0.0.0.0 --poll=1000 --watch"